# Install pre-commit hooks via
# pre-commit install

ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci 🤖] Apply code format tools to PR'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # frozen: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, toml, markdown, css, scss, javascript, json]
        args: [--prose-wrap=preserve]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 960ead214cd1184149d366c6d27ca6c369ce46b6 # frozen: 1.16.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f8a3f8c471fb698229face5ed7640a64900b781e # frozen: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: 6e41aba91fb32e9feb741a6258eefeb9c6e4a482 # frozen: v2.2.6
    hooks:
      - id: codespell
        args: ["-w"]
