name: 'Invite new members'
description: 'Read member list from YAML file and invite missing members'

inputs:
  token:
    description: 'A Github personal authentication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Invite missing members
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: >-
        pip install pyyaml requests;
        python ${{ github.action_path }}/invite-missing-members.py
